url: 
baseurl:

# Site settings
title: Data, Design and Society
email: ewanl@inf.ed.ac.uk
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Ewan Klein
  pic: 1
  position: Course Organiser
  social:
    - title: twitter
      url: ewanhklein
    # - title: facebook
    #   url: #
    # - title: stack-overflow
    #   url: #

- name: James Stewart
  pic: 2
  position: Lecturer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Alyssa Alcorn
  pic: 3
  position: Teaching Assistant
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/edinburghlivinglab

# Postal address (add as many lines as necessary)
address:
  - line: School of Informatics
  - line: University of Edinburgh

# Build settings
markdown: kramdown
permalink: pretty