url: 
baseurl:
#baseurl: /dds

# Site settings
title: Data, Design and Society
email: ewanl@inf.ed.ac.uk
description: "Site for University of Edinburgh Undergraduate Course"

# exclusion of _posts is temporary
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'THEME_LICENSE', 'mail', '_posts']

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Ewan Klein
  pic: ewan
  position: Course Organiser
  social:
    - title: twitter
      url: https://twitter.com/ewanhklein
    - title: linkedin
      url: https://uk.linkedin.com/in/ewanklein
    - title: github
      url: https://github.com/ewan-klein

- name: James Stewart
  pic: james
  position: Senior Research Fellow
  social:
    - title: twitter
      url: https://twitter.com/jamesks
    - title: facebook
      url: https://www.facebook.com/jameskstewart
    - title: linkedin
      url: https://uk.linkedin.com/in/jamesks

- name: Alyssa Alcorn
  pic: alyssa
  position: Teaching Assistant
  social:
    - title: twitter
      url: https://twitter.com/a_m_alcorn0131
    - title: facebook
      url: https://www.facebook.com/a.m.alcorn


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/edinburghlivinglab

# Postal address (add as many lines as necessary)
address:
  - line: School of Informatics
  - line: University of Edinburgh

# Build settings
markdown: kramdown
permalink: pretty